#!/usr/bin/env python3
"""
Build search index from HTML documentation files.

This script reads all HTML files in the docs/ directory, extracts their
content, and generates a search-index.js file for use with lunr.js.

Usage:
    python3 build-search-index.py
"""

import os
import re
import json
from pathlib import Path
from html.parser import HTMLParser

class ContentExtractor(HTMLParser):
    """Extract text content from HTML, ignoring script, style, and nav elements."""

    def __init__(self):
        super().__init__()
        self.content = []
        self.skip_tags = {'script', 'style', 'nav', 'div'}
        self.skip_classes = {'nav-bar', 'nav-header', 'nav-search', 'search-results', 'nav-links'}
        self.skip_current = False
        self.skip_depth = 0

    def handle_starttag(self, tag, attrs):
        # Check if we should skip this tag
        attrs_dict = dict(attrs)

        if tag in self.skip_tags:
            # Check if it's a nav-related div
            if tag == 'div' and 'class' in attrs_dict:
                classes = attrs_dict['class'].split()
                if any(c in self.skip_classes for c in classes):
                    self.skip_current = True
                    self.skip_depth = 1
                    return
        else:
            if self.skip_current:
                self.skip_depth += 1

    def handle_endtag(self, tag):
        if self.skip_current:
            self.skip_depth -= 1
            if self.skip_depth == 0:
                self.skip_current = False

    def handle_data(self, data):
        if not self.skip_current:
            text = data.strip()
            if text:
                self.content.append(text)

    def get_content(self):
        return ' '.join(self.content)

def extract_title(html):
    """Extract page title from HTML."""
    match = re.search(r'<title>(.*?)</title>', html, re.IGNORECASE | re.DOTALL)
    if match:
        title = match.group(1).strip()
        # Remove " - Documentation" suffix if present
        title = re.sub(r'\s*-\s*Documentation\s*$', '', title)
        return title
    return "Untitled"

def extract_content(html):
    """Extract text content from HTML."""
    extractor = ContentExtractor()
    extractor.feed(html)
    content = extractor.get_content()

    # Clean up whitespace
    content = re.sub(r'\s+', ' ', content)

    # Remove table of contents if present
    content = re.sub(r'Table of Contents.*?(?=\n\n|\Z)', '', content, flags=re.IGNORECASE | re.DOTALL)

    return content.strip()

def generate_search_index():
    """Generate search index from HTML files."""

    docs_dir = Path('docs')

    if not docs_dir.exists():
        print("Error: docs/ directory not found")
        return

    documents = []

    # Process each HTML file
    for html_file in sorted(docs_dir.glob('*.html')):
        print(f"Processing: {html_file.name}")

        try:
            with open(html_file, 'r', encoding='utf-8') as f:
                html = f.read()

            # Extract title and content
            title = extract_title(html)
            content = extract_content(html)

            # Create document object
            doc = {
                'id': html_file.stem,
                'title': title,
                'url': html_file.name,
                'body': content  # Full content for comprehensive search
            }

            documents.append(doc)
            print(f"  ✓ {title}")

        except Exception as e:
            print(f"  ✗ Error processing {html_file.name}: {e}")

    # Generate JavaScript file
    js_content = f"""/**
 * Search index auto-generated from HTML files
 * Generated by build-search-index.py
 *
 * To regenerate: python3 build-search-index.py
 */

const searchDocuments = {json.dumps(documents, indent=4)};
"""

    output_file = Path('search-index.js')
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"\n✓ Generated: {output_file}")
    print(f"  Indexed {len(documents)} documents")
    print(f"\nUpdate search.js to load this file:")
    print("  Add to HTML_HEAD: <script src=\"../search-index.js\"></script>")

if __name__ == '__main__':
    generate_search_index()
